#!/bin/sh

# Detects invalid pathname lengths and patterns based on restrictions from:
# POSIX Portable Filename Character Set,
# ustar pathname length restrictions,
# MS-DOS and Microsoft Windows restrictions,
# and additional restrictions to avoid common usability problems.

set -eu

# Only include ASCII characters in bracket expressions,
# and count length by bytes rather than characters.
export LC_COLLATE=C
export LC_CTYPE=C

# Propagate the value of LC_ALL to the environment
# without affecting the values of LC_COLLATE or LC_CTYPE.
if test "${LC_ALL-}"
then
	for i in LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME 
	do
		export "$i=$LC_ALL"
	done
	unset LC_ALL
fi

awk '
	function alength(arr,    i, j)
	{
		i = 0
		for (j in arr) {
			++i
		}
		return i
	}

	function adelete(arr,    i)
	{
		for (i in arr) {
			delete arr[i]
		}
	}

	BEGIN {
		FS = "/"
		EXIT_SUCCESS = 0
		EXIT_FAILURE = 1
		status = EXIT_SUCCESS
		format = "%s: %s: %s\n"
		filter = "sort"

		# array[criteria] = "error message prefix"
		byte[byte_pref = 156] = "Exceeds ustar prefix byte limit"
		byte[byte_name = 100] = "Exceeds ustar filename byte limit"
		patt["[^0-9A-Za-z._-]"] = "Contains non-portable character"
		patt["^-|[.]$"] = "Invalid leading/trailing character"
		patt["^[^0-9A-Za-z]+$"] = "Only contains"
		patt["^(aux|con|nul|prn|(com|lpt)[0-9])([.].*)?$"] = \
			"Reserved MS-DOS name"
		patt["^[.]lock$|_vti_|^desktop[.]ini$"] = \
			"Restricted Microsoft OneDrive name"

		for (i = 1; i < ARGC; ++i) {
			path = ARGV[i]
			n = split(path, comp)

			if (n > 1 && length(path) - length(comp[n]) > byte_pref) {
				flag[byte_pref] = byte[byte_pref]
			}

			for (j = 1; j <= n; ++j) {
				if (comp[j] != "") {
					if (length(comp[j]) > byte_name) {
						flag[byte_name] = byte[byte_name]
					}
					for (k in patt) {
						if (tolower(comp[j]) ~ k) {
							flag[k] = patt[k]
						}
					}
				}
			}

			if (alength(flag) > 0) {
				status = EXIT_FAILURE
				for (j in flag) {
					printf format, path, flag[j], j | filter
				}
				close(filter)
				adelete(flag)
			}
		}

		exit status
	}
' "$@"
