#!/bin/sh

# Detect invalid and problematic pathname lengths and patterns,
# accounting for both unix-like and Microsoft OSes.

# Only include ASCII characters in bracket expressions,
# and count length by bytes rather than characters.
export LC_COLLATE=C
export LC_CTYPE=C

# Propagate the value of LC_ALL to the environment
# without affecting the values of LC_COLLATE or LC_CTYPE.
if [ "$LC_ALL" ]
then
	for i in LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME 
	do
		export "$i=$LC_ALL"
	done
	unset LC_ALL
fi

awk '
	BEGIN {
		FS = "/"
		EXIT_SUCCESS = 0
		EXIT_FAILURE = 1
		status = EXIT_SUCCESS
		format = "%s: %s: \47%s\47\n"
		filter = "sort"

		# array[criteria] = "error message prefix"
		byte[byte_pref = 156] = "exceeds ustar prefix byte limit"
		byte[byte_name = 100] = "exceeds ustar filename byte limit"
		patt["[^0-9A-Za-z._-]"] = \
			"contains character not from the " \
			"POSIX Portable Filename Character Set"
		patt["^-"] = \
			"contains problematic leading character on " \
			"unix-like OSes"
		patt["[ .]$"] = \
			"contains disallowed trailing character on " \
			"Microsoft OSes"
		patt["^(aux|con|nul|prn|(com|lpt)[0-9])([.].*)?$"] = \
			"reserved MS-DOS name"
		patt["^[.]lock$|_vti_|^desktop[.]ini$"] = \
			"restricted Microsoft OneDrive name"

		# Special pathname components to ignore.
		++spec[""]
		++spec["."]
		++spec[".."]

		for (i = 1; i < ARGC; ++i) {
			path = ARGV[i]
			n = split(path, comp)

			if (n > 1 && length(path) - length(comp[n]) > byte_pref) {
				flag[byte_pref] = byte[byte_pref]
			}

			for (c = 1; c <= n; ++c) {
				if (!(comp[c] in spec)) {
					if (length(comp[c]) > byte_name) {
						flag[byte_name] = byte[byte_name]
					}
					for (p in patt) {
						if (tolower(comp[c]) ~ p) {
							flag[p] = patt[p]
						}
					}
				}
			}

			if (alength(flag)) {
				status = EXIT_FAILURE
				for (f in flag) {
					printf format, path, flag[f], f | filter
				}
				close(filter)
				adelete(flag)
			}
		}

		exit status
	}

	function alength(arr,    i, j)
	{
		for (i in arr) {
			++j
		}
		return j
	}

	function adelete(arr,    i)
	{
		for (i in arr) {
			delete arr[i]
		}
	}
' "$@"
