= aproname

Detects problematic pathname patterns,
accounting for both unix-like and Microsoft OSes.

Restrictions include:

. POSIX Portable Filename Character Set
. Ustar pathname length restrictions
. MS-DOS and Microsoft Windows restrictions
. additional restrictions to avoid common usability problems

Invalid pathnames are printed to STDOUT with a summary of problems for each one.

== Usage

`aproname [file...]`

As an awk script,
aproname expects input in one of two ways:

. from STDIN,
. as arguments,
  where each argument is treated as a file,
  and where each file is expected to contain pathnames.
  The pathname of the argument itself is not checked for invalid patterns.

To check the pathnames in a directory tree:

`find path | aproname`

The script returns exit code 1 if any problematic patterns are found.

== Bugs

Aproname can not properly handle embedded newlines.
Such a pathname will be incorrectly treated as two or more pathnames.

== References

* https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/V1_chap03.html#tag_03_282[POSIX Portable Filename Character Set]
* https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/pax.html#tag_20_92_13_06[Ustar format]
* https://mgorny.pl/articles/portability-of-tar-features.html[Ustar portability]
* https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file[Microsoft Windows filenames]
* https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa[Microsoft OneDrive filenames]
* https://dwheeler.com/essays/fixing-unix-linux-filenames.html[Commentary on safe filenames]
