= aproname

Detects problematic pathname patterns,
accounting for both unix-like and Microsoft OSes.

Restrictions include:

. POSIX Portable Filename Character Set,
. ustar pathname length restrictions,
. MS-DOS and Microsoft Windows restrictions,
. additional restrictions to avoid common usability problems.

Invalid pathnames are printed to STDOUT with a summary of problems for each one.

== Usage

`aproname [file...]`

As an `awk` script,
`aproname` expects input in one of two ways:

. from STDIN,
. as arguments,
  where each argument is treated as a file,
  and where each file is expected to contain pathnames.
  The pathname of the argument itself is not checked for invalid patterns.

To check the pathnames in a directory tree:

`find path | aproname`

`aproname` can not properly handle embedded newlines.
Such a pathname will be incorrectly treated as two or more pathnames.

The script returns exit code 1 if any problematic patterns are found.

== Requirements

POSIX `awk`, `sh`, and utilities.

== TODO

The `bytes` function is very slow due to calling external utilities.
Replacing it with something better would speed up the script significantly.
